=== mrMigles/birthday.bot/src/main/resources/settings/settings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        targetNamespace="urn:birthdaybot:1.0"
        xmlns="urn:birthdaybot:1.0"
        elementFormDefault="qualified"
        attributeFormDefault="unqualified"
        version="1.0">
  <xsd:element name="birthdayBot">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="login"/>
        <xsd:element ref="interval"/>
        <xsd:element ref="sendRequestMessage"/>
        <xsd:element ref="skypeLiveInMinutesBeforeReload"/>
        <xsd:element ref="schedulingTime"/>
        <xsd:element ref="contacts"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="bDay" type="xsd:date"/>
  <xsd:element name="skype" type="xsd:string"/>
  <xsd:element name="topicName" type="xsd:string"/>
  <xsd:element name="isAdmin" type="xsd:boolean"/>
  <xsd:element name="contact">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="skype"/>
        <xsd:element ref="bDay"/>
        <xsd:element ref="topicName"/>
        <xsd:element ref="isAdmin"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="login" type="xsd:string"/>
  <xsd:element name="interval" type="xsd:positiveInteger"/>
  <xsd:element name="sendRequestMessage" type="xsd:string"/>
  <xsd:element name="skypeLiveInMinutesBeforeReload" type="xsd:positiveInteger"/>
  <xsd:element name="schedulingTime" type="xsd:string"/>

  <xsd:element name="contacts">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="contact" maxOccurs="unbounded" minOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== mrMigles/birthday.bot/src/main/resources/settings/settings.xml
<?xml version="1.0" encoding="UTF-8"?>

<birthdayBot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="urn:birthdaybot:1.0"
             xsi:schemaLocation="settings.xsd">

    <login>yor_bot_skype_login</login>
    <interval>30</interval>
    <sendRequestMessage>Hi, I'm bot</sendRequestMessage>
    <updateTokenMinutes>600</updateTokenMinutes>
    <schedulingTime>10:00</schedulingTime>

    <contacts>
        <contact>
            <skype>John Smith</skype>
            <bDay>1999-09-09</bDay>
            <topicName>John S.</topicName>
        </contact>
        <contact>
            <skype>John Connor</skype>
            <bDay>1999-09-09</bDay>
            <topicName>John C.</topicName>
        </contact>
    </contacts>
</birthdayBot>
